### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by zxcvqwerasdf** [ExistedGit/Dota2Dumper#2]
![image](https://github.com/ExistedGit/Dota2Dumper/assets/67195196/afc92bff-8b6e-4985-87df-5209d169a487)
How to debug this error?

**Comment by zxcvqwerasdf** [comment]
Seems like offset is outdated
![image](https://github.com/ExistedGit/Dota2Dumper/assets/67195196/f9330ebf-24f4-4c39-825e-36b892ebc72a)

**Comment by zxcvqwerasdf** [comment]
![image](https://github.com/ExistedGit/Dota2Dumper/assets/67195196/54a3c377-c42a-41d7-b368-bfb306a733e9)

**Comment by ExistedGit** [comment]
I'll try and look into it, seems there were some cheat-breaking changes after all
